openapi: 3.0.0
info:
  title: Slaschapp API Documentation
  contact: {}
  version: '1.0'
servers:
- url: https://adlinc-api.onrender.com/api/slaschapp
  variables: {}
paths:
  /auth/register/user:
    post:
      tags:
      - Authentication User
      summary: Register User Profile
      operationId: RegisterUserProfile
      parameters: []
      requestBody:
        description: ''
        content:
          application/json:
            schema:
              allOf:
              - $ref: '#/components/schemas/RegisterUserProfileRequest'
              - example:
                  firstname: tank
                  secondname: michael
                  surname: davis
                  profilePicture: https://images.pexels.com/photos/5764701/pexels-photo-5764701.png?auto=compress&cs=tinysrgb&w=600
                  phoneNumber: '076981284'
                  email: tank@gmail.com
                  password: davis
                  AcceptTermsAndConditions: Yes
                  locationOrAddress: Durban,South Africa
                  birthday: 1996/07/12
                  educationStatus: Tertiary
                  gender: male
                  wallet: Capitec Wallet
                  interests: Food And Drinks
            example:
              firstname: tank
              secondname: michael
              surname: davis
              profilePicture: https://images.pexels.com/photos/5764701/pexels-photo-5764701.png?auto=compress&cs=tinysrgb&w=600
              phoneNumber: '076981284'
              email: tank@gmail.com
              password: davis
              AcceptTermsAndConditions: Yes
              locationOrAddress: Durban,South Africa
              birthday: 1996/07/12
              educationStatus: Tertiary
              gender: male
              wallet: Capitec Wallet
              interests: Food And Drinks
        required: true
      responses:
        '200':
          description: ''
          headers: {}
      deprecated: false
      security: []
      servers:
      - url: https://adlinc-api.onrender.com/api/slaschapp
        variables: {}
  /auth/login/user:
    post:
      tags:
      - Authentication User
      summary: Login User
      operationId: LoginUser
      parameters: []
      requestBody:
        description: ''
        content:
          application/json:
            schema:
              allOf:
              - $ref: '#/components/schemas/LoginUserRequest'
              - example:
                  email: lizwi@gmail.com
                  password: lizwi123
            example:
              email: lizwi@gmail.com
              password: lizwi123
        required: true
      responses:
        '200':
          description: ''
          headers: {}
      deprecated: false
      security: []
      servers:
      - url: https://adlinc-api.onrender.com/api/slaschapp
        variables: {}
  /auth/login/user/reset/{resetToken}:
    patch:
      tags:
      - Authentication User
      summary: User Password Reset
      operationId: UserPasswordReset
      parameters:
      - name: resetToken
        in: path
        description: ''
        required: true
        style: simple
        schema:
          type: string
      requestBody:
        description: ''
        content:
          application/json:
            schema:
              allOf:
              - $ref: '#/components/schemas/UserPasswordResetRequest'
              - example:
                  newPassword: lizwi
                  email: saliba@gmail.com
            example:
              newPassword: lizwi
              email: saliba@gmail.com
        required: true
      responses:
        '200':
          description: ''
          headers: {}
      deprecated: false
      security: []
      servers:
      - url: https://adlinc-api.onrender.com/api/slaschapp
        variables: {}
  /auth/login/user/forgot:
    patch:
      tags:
      - Authentication User
      summary: User Forgot Password
      operationId: UserForgotPassword
      parameters: []
      requestBody:
        description: ''
        content:
          application/json:
            schema:
              allOf:
              - $ref: '#/components/schemas/UserForgotPasswordRequest'
              - example:
                  email: saliba@gmail.com
            example:
              email: saliba@gmail.com
        required: true
      responses:
        '200':
          description: ''
          headers: {}
      deprecated: false
      security: []
      servers:
      - url: https://adlinc-api.onrender.com/api/slaschapp
        variables: {}
  /business:
    post:
      tags:
      - Businesses
      summary: Create Business
      operationId: CreateBusiness
      parameters: []
      requestBody:
        description: ''
        content:
          application/json:
            schema:
              allOf:
              - $ref: '#/components/schemas/CreateBusinessRequest'
              - example:
                  BusinessName: Lizwi's Tech Store
                  PhoneNumber: '04486899921'
                  BusinessEmail: LizwiTech@gmail.com
                  AcceptTermsAndConditions: Yes
                  BusinessCategory: Tech And Electronics
                  BusinessLocation: Durban,KwaZulu-Natal
                  BusinessHours: 07:00-16:00,Mon-Fri
                  BusinessLogo: https://images.pexels.com/photos/2417848/pexels-photo-2417848.jpeg?auto=compress&cs=tinysrgb&w=600
                  verificationDoc: https://media.istockphoto.com/id/1448013633/photo/employment-eligibility-verification-form.jpg?b=1&s=612x612&w=0&k=20&c=wIqK_DjjZcFjSmL4Jf9SZ-FAN0MF32DZEhsxllGk1GY=
                  status: Active
                  socials: facebook
            example:
              BusinessName: Lizwi's Tech Store
              PhoneNumber: '04486899921'
              BusinessEmail: LizwiTech@gmail.com
              AcceptTermsAndConditions: Yes
              BusinessCategory: Tech And Electronics
              BusinessLocation: Durban,KwaZulu-Natal
              BusinessHours: 07:00-16:00,Mon-Fri
              BusinessLogo: https://images.pexels.com/photos/2417848/pexels-photo-2417848.jpeg?auto=compress&cs=tinysrgb&w=600
              verificationDoc: https://media.istockphoto.com/id/1448013633/photo/employment-eligibility-verification-form.jpg?b=1&s=612x612&w=0&k=20&c=wIqK_DjjZcFjSmL4Jf9SZ-FAN0MF32DZEhsxllGk1GY=
              status: Active
              socials: facebook
        required: true
      responses:
        '200':
          description: ''
          headers: {}
      deprecated: false
      security:
      - bearer: []
      servers:
      - url: https://adlinc-api.onrender.com/api/slaschapp
        variables: {}
    get:
      tags:
      - Businesses
      summary: Get All Businesses
      operationId: GetAllBusinesses
      parameters: []
      responses:
        '200':
          description: ''
          headers: {}
      deprecated: false
      security:
      - bearer: []
      servers:
      - url: https://adlinc-api.onrender.com/api/slaschapp
        variables: {}
  /business/{businessID}:
    get:
      tags:
      - Businesses
      summary: Get Single Business
      operationId: GetSingleBusiness
      parameters:
      - name: businessID
        in: path
        description: ''
        required: true
        style: simple
        schema:
          type: string
      responses:
        '200':
          description: ''
          headers: {}
      deprecated: false
      security:
      - bearer: []
      servers:
      - url: https://adlinc-api.onrender.com/api/slaschapp
        variables: {}
    patch:
      tags:
      - Businesses
      summary: Delete Business
      operationId: DeleteBusiness
      parameters:
      - name: businessID
        in: path
        description: ''
        required: true
        style: simple
        schema:
          type: string
      responses:
        '200':
          description: ''
          headers: {}
      deprecated: false
      servers:
      - url: https://adlinc-api.onrender.com/api/slaschapp
        variables: {}
  /search:
    get:
      tags:
      - Businesses
      summary: Business Search
      operationId: BusinessSearch
      parameters:
      - name: BusinessCategory
        in: query
        description: ''
        required: true
        style: form
        explode: true
        schema:
          type: string
          example: Beauty
      responses:
        '200':
          description: ''
          headers: {}
      deprecated: false
      servers:
      - url: https://adlinc-api.onrender.com/api/slaschapp
        variables: {}
  /business/6634bfb784e9bf0c9788e950/auction:
    post:
      tags:
      - Auctions
      summary: Create Auction
      operationId: CreateAuction
      parameters: []
      requestBody:
        description: ''
        content:
          application/json:
            schema:
              allOf:
              - $ref: '#/components/schemas/CreateAuctionRequest'
              - example:
                  campaignName: Fashion Festival
                  campaignDescription: Fashion Festival For The Ages
                  campaignBudget: 58000
                  campaignDailyBudget: 5000
                  campaignStartDate: 22 October 2024
                  interests: Technology
            example:
              campaignName: Fashion Festival
              campaignDescription: Fashion Festival For The Ages
              campaignBudget: 58000
              campaignDailyBudget: 5000
              campaignStartDate: 22 October 2024
              interests: Technology
        required: true
      responses:
        '200':
          description: ''
          headers: {}
      deprecated: false
      security:
      - bearer: []
      servers:
      - url: https://adlinc-api.onrender.com/api/slaschapp
        variables: {}
  /business/{ownerID}/search/auction:
    get:
      tags:
      - Auctions
      summary: Auction Search
      operationId: AuctionSearch
      parameters:
      - name: campaignName
        in: query
        description: ''
        required: true
        style: form
        explode: true
        schema:
          type: string
          example: Stake
      - name: campaignBudget
        in: query
        description: ''
        required: true
        style: form
        explode: true
        schema:
          type: string
          example: R500
      - name: ownerID
        in: path
        description: ''
        required: true
        style: simple
        schema:
          type: string
      responses:
        '200':
          description: ''
          headers: {}
      deprecated: false
      servers:
      - url: https://adlinc-api.onrender.com/api/slaschapp
        variables: {}
  /business/{ownerID}/auction/{auctionID}:
    patch:
      tags:
      - Auctions
      summary: Update Auction
      operationId: UpdateAuction
      parameters:
      - name: ownerID
        in: path
        description: ''
        required: true
        style: simple
        schema:
          type: string
      - name: auctionID
        in: path
        description: ''
        required: true
        style: simple
        schema:
          type: string
      requestBody:
        description: ''
        content:
          application/json:
            schema:
              allOf:
              - $ref: '#/components/schemas/UpdateAuctionRequest'
              - example:
                  campaignName: ''
                  campaignDescription: ''
                  campaignBudget: ''
                  campaignDailyBudget: ''
                  campaignStartDate: ''
                  checkInStoreAvailability: ''
                  percentageDiscount: ''
                  interests: ''
                  baitPlant:
                    name: ''
                    baitPlantDescription: ''
                    price: ''
                    photos: ''
            example:
              campaignName: ''
              campaignDescription: ''
              campaignBudget: ''
              campaignDailyBudget: ''
              campaignStartDate: ''
              checkInStoreAvailability: ''
              percentageDiscount: ''
              interests: ''
              baitPlant:
                name: ''
                baitPlantDescription: ''
                price: ''
                photos: ''
        required: true
      responses:
        '200':
          description: ''
          headers: {}
      deprecated: false
      servers:
      - url: https://adlinc-api.onrender.com/api/slaschapp
        variables: {}
    get:
      tags:
      - Auctions
      summary: Get Single Auction
      operationId: GetSingleAuction
      parameters:
      - name: ownerID
        in: path
        description: ''
        required: true
        style: simple
        schema:
          type: string
      - name: auctionID
        in: path
        description: ''
        required: true
        style: simple
        schema:
          type: string
      responses:
        '200':
          description: ''
          headers: {}
      deprecated: false
      security:
      - bearer: []
      servers:
      - url: https://adlinc-api.onrender.com/api/slaschapp
        variables: {}
  /business/{ownerID}/auction:
    get:
      tags:
      - Auctions
      summary: Get All Auctions
      operationId: GetAllAuctions
      parameters:
      - name: ownerID
        in: path
        description: ''
        required: true
        style: simple
        schema:
          type: string
      responses:
        '200':
          description: ''
          headers: {}
      deprecated: false
      security:
      - bearer: []
      servers:
      - url: https://adlinc-api.onrender.com/api/slaschapp
        variables: {}
  /business/owner/{ownerID}:
    patch:
      tags:
      - Business Owner
      summary: Update Business Owner
      operationId: UpdateBusinessOwner
      parameters:
      - name: ownerID
        in: path
        description: ''
        required: true
        style: simple
        schema:
          type: string
      requestBody:
        description: ''
        content:
          application/json:
            schema:
              allOf:
              - $ref: '#/components/schemas/UpdateBusinessOwnerRequest'
              - example:
                  firstname: Carlos
                  secondname: Alberto
                  surname: Riberio
                  profilePicture: Lucas's photo string
                  phoneNumber: '0812344905'
                  email: lucasR@gmail.com
                  password: lucas123
                  AcceptTermsAndConditions: Yes
                  locationOrAddress: Cairo,Egypt
                  birthday: 27/09/1975
                  IdNumber: '8905285921090'
                  IdDocumentLink: document link
                  gender: male
                  resetToken: generated by forgot password
                  resetTokenExpiration: generated by forgot password endpoint
            example:
              firstname: Carlos
              secondname: Alberto
              surname: Riberio
              profilePicture: Lucas's photo string
              phoneNumber: '0812344905'
              email: lucasR@gmail.com
              password: lucas123
              AcceptTermsAndConditions: Yes
              locationOrAddress: Cairo,Egypt
              birthday: 27/09/1975
              IdNumber: '8905285921090'
              IdDocumentLink: document link
              gender: male
              resetToken: generated by forgot password
              resetTokenExpiration: generated by forgot password endpoint
        required: true
      responses:
        '200':
          description: ''
          headers: {}
      deprecated: false
      servers:
      - url: https://adlinc-api.onrender.com/api/slaschapp
        variables: {}
    get:
      tags:
      - Business Owner
      summary: Get Single Business Owner
      operationId: GetSingleBusinessOwner
      parameters:
      - name: ownerID
        in: path
        description: ''
        required: true
        style: simple
        schema:
          type: string
      responses:
        '200':
          description: ''
          headers: {}
      deprecated: false
      servers:
      - url: https://adlinc-api.onrender.com/api/slaschapp
        variables: {}
  /business/owner:
    get:
      tags:
      - Business Owner
      summary: Get All Business Owners
      operationId: GetAllBusinessOwners
      parameters: []
      responses:
        '200':
          description: ''
          headers: {}
      deprecated: false
      servers:
      - url: https://adlinc-api.onrender.com/api/slaschapp
        variables: {}
  /auth/register/owner:
    post:
      tags:
      - Authentication Business Owner
      summary: Register Business Owner Profile
      operationId: RegisterBusinessOwnerProfile
      parameters: []
      requestBody:
        description: ''
        content:
          application/json:
            schema:
              allOf:
              - $ref: '#/components/schemas/RegisterBusinessOwnerProfileRequest'
              - example:
                  firstname: peter
                  secondname: king
                  surname: peterson
                  profilePicture: https://images.pexels.com/photos/733872/pexels-photo-733872.jpeg?auto=compress&cs=tinysrgb&w=600
                  phoneNumber: '34'
                  email: peterson@gmail.com
                  password: mathews12
                  AcceptTermsAndConditions: Yes
                  locationOrAddress: Johannesburg,South Africa
                  birthday: 27/09/1985
                  IdNumber: '8905285921090'
                  IdDocumentLink: document link
                  gender: male
            example:
              firstname: peter
              secondname: king
              surname: peterson
              profilePicture: https://images.pexels.com/photos/733872/pexels-photo-733872.jpeg?auto=compress&cs=tinysrgb&w=600
              phoneNumber: '34'
              email: peterson@gmail.com
              password: mathews12
              AcceptTermsAndConditions: Yes
              locationOrAddress: Johannesburg,South Africa
              birthday: 27/09/1985
              IdNumber: '8905285921090'
              IdDocumentLink: document link
              gender: male
        required: true
      responses:
        '200':
          description: ''
          headers: {}
      deprecated: false
      security: []
      servers:
      - url: https://adlinc-api.onrender.com/api/slaschapp
        variables: {}
  /auth/login/owner:
    post:
      tags:
      - Authentication Business Owner
      summary: Login Business Owner
      operationId: LoginBusinessOwner
      parameters: []
      requestBody:
        description: ''
        content:
          application/json:
            schema:
              allOf:
              - $ref: '#/components/schemas/LoginBusinessOwnerRequest'
              - example:
                  email: lizwi@gmail.com
                  password: lizwi123
            example:
              email: lizwi@gmail.com
              password: lizwi123
        required: true
      responses:
        '200':
          description: ''
          headers: {}
      deprecated: false
      security: []
      servers:
      - url: https://adlinc-api.onrender.com/api/slaschapp
        variables: {}
  /auth/login/owner/reset/{resetToken}:
    patch:
      tags:
      - Authentication Business Owner
      summary: Business Owner Password Reset
      operationId: BusinessOwnerPasswordReset
      parameters:
      - name: resetToken
        in: path
        description: ''
        required: true
        style: simple
        schema:
          type: string
      requestBody:
        description: ''
        content:
          application/json:
            schema:
              allOf:
              - $ref: '#/components/schemas/BusinessOwnerPasswordResetRequest'
              - example:
                  newPassword: lizwi
                  email: saliba@gmail.com
            example:
              newPassword: lizwi
              email: saliba@gmail.com
        required: true
      responses:
        '200':
          description: ''
          headers: {}
      deprecated: false
      security: []
      servers:
      - url: https://adlinc-api.onrender.com/api/slaschapp
        variables: {}
  /auth/login/owner/forgot:
    patch:
      tags:
      - Authentication Business Owner
      summary: Business Owner Forgot Password
      operationId: BusinessOwnerForgotPassword
      parameters: []
      requestBody:
        description: ''
        content:
          application/json:
            schema:
              allOf:
              - $ref: '#/components/schemas/BusinessOwnerForgotPasswordRequest'
              - example:
                  email: saliba@gmail.com
            example:
              email: saliba@gmail.com
        required: true
      responses:
        '200':
          description: ''
          headers: {}
      deprecated: false
      security: []
      servers:
      - url: https://adlinc-api.onrender.com/api/slaschapp
        variables: {}
  /data/collection/start:
    post:
      tags:
      - Data Collection
      summary: Start Data Collection
      operationId: StartDataCollection
      parameters: []
      responses:
        '200':
          description: ''
          headers: {}
      deprecated: false
      security: []
      servers:
      - url: https://adlinc-api.onrender.com/api/slaschapp
        variables: {}
  /data/collection/stop:
    post:
      tags:
      - Data Collection
      summary: Stop Data Collection
      operationId: StopDataCollection
      parameters: []
      responses:
        '200':
          description: ''
          headers: {}
      deprecated: false
      security: []
      servers:
      - url: https://adlinc-api.onrender.com/api/slaschapp
        variables: {}
  /admin/users:
    get:
      tags:
      - Admin
      summary: Get All Users
      operationId: GetAllUsers
      parameters: []
      responses:
        '200':
          description: ''
          headers: {}
      deprecated: false
      security: []
      servers:
      - url: https://adlinc-api.onrender.com/api/slaschapp
        variables: {}
  /admin/businesses:
    get:
      tags:
      - Admin
      summary: Get All Businesses
      operationId: GetAllBusinesses1
      parameters: []
      responses:
        '200':
          description: ''
          headers: {}
      deprecated: false
      security: []
      servers:
      - url: https://adlinc-api.onrender.com/api/slaschapp
        variables: {}
  /admin/owners:
    get:
      tags:
      - Admin
      summary: Get All Business Owners
      operationId: GetAllBusinessOwners1
      parameters: []
      responses:
        '200':
          description: ''
          headers: {}
      deprecated: false
      security: []
      servers:
      - url: https://adlinc-api.onrender.com/api/slaschapp
        variables: {}
  /admin/category:
    get:
      tags:
      - Admin
      summary: Get All Categories
      operationId: GetAllCategories
      parameters: []
      responses:
        '200':
          description: ''
          headers: {}
      deprecated: false
      security: []
      servers:
      - url: https://adlinc-api.onrender.com/api/slaschapp
        variables: {}
  /admin/baits:
    get:
      tags:
      - Admin
      summary: Get All Bait Plants
      operationId: GetAllBaitPlants
      parameters: []
      responses:
        '200':
          description: ''
          headers: {}
      deprecated: false
      security: []
      servers:
      - url: https://adlinc-api.onrender.com/api/slaschapp
        variables: {}
  /admin/bait/{baitID}:
    patch:
      tags:
      - Admin
      summary: Update Category
      operationId: UpdateCategory
      parameters:
      - name: baitID
        in: path
        description: ''
        required: true
        style: simple
        schema:
          type: string
      responses:
        '200':
          description: ''
          headers: {}
      deprecated: false
      security: []
      servers:
      - url: https://adlinc-api.onrender.com/api/slaschapp
        variables: {}
  /admin/auctions:
    get:
      tags:
      - Admin
      summary: Get All Auctions
      operationId: GetAllAuctions1
      parameters: []
      responses:
        '200':
          description: ''
          headers: {}
      deprecated: false
      security: []
      servers:
      - url: https://adlinc-api.onrender.com/api/slaschapp
        variables: {}
  /admin/carts:
    get:
      tags:
      - Admin
      summary: Get All Carts
      operationId: GetAllCarts
      parameters: []
      responses:
        '200':
          description: ''
          headers: {}
      deprecated: false
      security: []
      servers:
      - url: https://adlinc-api.onrender.com/api/slaschapp
        variables: {}
  /business/auction/{auctionID}/bait/create:
    post:
      tags:
      - Bait Plants
      summary: Create Bait Plant
      operationId: CreateBaitPlant
      parameters:
      - name: auctionID
        in: path
        description: ''
        required: true
        style: simple
        schema:
          type: string
      requestBody:
        description: ''
        content:
          application/json:
            schema:
              allOf:
              - $ref: '#/components/schemas/CreateBaitPlantRequest'
              - example:
                  baitPlantName: Gaming Bait
                  baitPlantDescription: Exclusive Gaming Bait
                  checkInStoreAvailability: Yes
                  percentageDiscount: 13%
                  price: R800
                  color: black
                  size: large
                  photos:
                  - https://images.pexels.com/photos/3945688/pexels-photo-3945688.jpeg?auto=compress&cs=tinysrgb&w=600
                  - https://images.pexels.com/photos/1082810/pexels-photo-1082810.jpeg?auto=compress&cs=tinysrgb&w=600
                  - https://images.pexels.com/photos/3593986/pexels-photo-3593986.jpeg?auto=compress&cs=tinysrgb&w=600
                  - https://images.pexels.com/photos/3945659/pexels-photo-3945659.jpeg?auto=compress&cs=tinysrgb&w=600
            example:
              baitPlantName: Gaming Bait
              baitPlantDescription: Exclusive Gaming Bait
              checkInStoreAvailability: Yes
              percentageDiscount: 13%
              price: R800
              color: black
              size: large
              photos:
              - https://images.pexels.com/photos/3945688/pexels-photo-3945688.jpeg?auto=compress&cs=tinysrgb&w=600
              - https://images.pexels.com/photos/1082810/pexels-photo-1082810.jpeg?auto=compress&cs=tinysrgb&w=600
              - https://images.pexels.com/photos/3593986/pexels-photo-3593986.jpeg?auto=compress&cs=tinysrgb&w=600
              - https://images.pexels.com/photos/3945659/pexels-photo-3945659.jpeg?auto=compress&cs=tinysrgb&w=600
        required: true
      responses:
        '200':
          description: ''
          headers: {}
      deprecated: false
      security: []
      servers:
      - url: https://adlinc-api.onrender.com/api/slaschapp
        variables: {}
  /bait/auction/{auctionID}/bait:
    get:
      tags:
      - Bait Plants
      summary: Get All Bait Plants
      operationId: GetAllBaitPlants1
      parameters:
      - name: auctionID
        in: path
        description: ''
        required: true
        style: simple
        schema:
          type: string
      responses:
        '200':
          description: ''
          headers: {}
      deprecated: false
      security: []
      servers:
      - url: https://adlinc-api.onrender.com/api/slaschapp
        variables: {}
  /bait/auction/{auctionID}/bait/{baitID}:
    get:
      tags:
      - Bait Plants
      summary: Get Single Bait Plant
      operationId: GetSingleBaitPlant
      parameters:
      - name: auctionID
        in: path
        description: ''
        required: true
        style: simple
        schema:
          type: string
      - name: baitID
        in: path
        description: ''
        required: true
        style: simple
        schema:
          type: string
      responses:
        '200':
          description: ''
          headers: {}
      deprecated: false
      security: []
      servers:
      - url: https://adlinc-api.onrender.com/api/slaschapp
        variables: {}
    patch:
      tags:
      - Bait Plants
      summary: Delete Single Bait
      operationId: DeleteSingleBait
      parameters:
      - name: auctionID
        in: path
        description: ''
        required: true
        style: simple
        schema:
          type: string
      - name: baitID
        in: path
        description: ''
        required: true
        style: simple
        schema:
          type: string
      responses:
        '200':
          description: ''
          headers: {}
      deprecated: false
      security: []
      servers:
      - url: https://adlinc-api.onrender.com/api/slaschapp
        variables: {}
  /business/auction/{auctionID}/bait/{baitID}:
    patch:
      tags:
      - Bait Plants
      summary: Update Bait Plant
      operationId: UpdateBaitPlant
      parameters:
      - name: auctionID
        in: path
        description: ''
        required: true
        style: simple
        schema:
          type: string
      - name: baitID
        in: path
        description: ''
        required: true
        style: simple
        schema:
          type: string
      requestBody:
        description: ''
        content:
          application/json:
            schema:
              allOf:
              - $ref: '#/components/schemas/UpdateBaitPlantRequest'
              - example:
                  name: Data Specialist
                  baitPlantDescription: Python,SQL and Analytics
                  checkInStoreAvailability: Yes
                  percentageDiscount: 44%
                  price: R75
                  color: Purple
                  size: Small
                  photos:
                  - black image
            example:
              name: Data Specialist
              baitPlantDescription: Python,SQL and Analytics
              checkInStoreAvailability: Yes
              percentageDiscount: 44%
              price: R75
              color: Purple
              size: Small
              photos:
              - black image
        required: true
      responses:
        '200':
          description: ''
          headers: {}
      deprecated: false
      security: []
      servers:
      - url: https://adlinc-api.onrender.com/api/slaschapp
        variables: {}
  /user/{userID}:
    get:
      tags:
      - Profiles
      summary: User Profile
      operationId: UserProfile
      parameters:
      - name: userID
        in: path
        description: ''
        required: true
        style: simple
        schema:
          type: string
      responses:
        '200':
          description: ''
          headers: {}
      deprecated: false
      servers:
      - url: https://adlinc-api.onrender.com/api/slaschapp
        variables: {}
    patch:
      tags:
      - Profiles
      summary: Delete User Profile
      operationId: DeleteUserProfile
      parameters:
      - name: userID
        in: path
        description: ''
        required: true
        style: simple
        schema:
          type: string
      responses:
        '200':
          description: ''
          headers: {}
      deprecated: false
      servers:
      - url: https://adlinc-api.onrender.com/api/slaschapp
        variables: {}
  /profile/user/history:
    patch:
      tags:
      - Profiles
      summary: Suspend The Profile
      operationId: SuspendTheProfile
      parameters: []
      responses:
        '200':
          description: ''
          headers: {}
      deprecated: false
      servers:
      - url: https://adlinc-api.onrender.com/api/slaschapp
        variables: {}
    get:
      tags:
      - Profiles
      summary: Get All Past Orders
      operationId: GetAllPastOrders
      parameters: []
      responses:
        '200':
          description: ''
          headers: {}
      deprecated: false
      security:
      - bearer: []
      servers:
      - url: https://adlinc-api.onrender.com/api/slaschapp
        variables: {}
  /cart/{cartId}:
    get:
      tags:
      - Cart
      summary: Get Order
      operationId: GetOrder
      parameters:
      - name: cartId
        in: path
        description: ''
        required: true
        style: simple
        schema:
          type: string
      responses:
        '200':
          description: ''
          headers: {}
      deprecated: false
      security:
      - bearer: []
      servers:
      - url: https://adlinc-api.onrender.com/api/slaschapp
        variables: {}
  /cart/add-bait:
    post:
      tags:
      - Cart
      summary: Add Bait To Cart
      operationId: AddBaitToCart
      parameters: []
      requestBody:
        description: ''
        content:
          application/json:
            schema:
              allOf:
              - $ref: '#/components/schemas/AddBaitToCartRequest'
              - example:
                  auctionName: Tech Festival
                  auctionId: 664cc923e5a1e4b89b7ba353
                  status: Pending
                  baits:
                  - baitId: 6650b8973c45cee34da207cf
                    baitName: Mzansi Bait
                    price: 800
                    quantity: 5
                    size: large
                    color: black
                  - baitId: 6650b8663c45cee34da207cd
                    baitName: Sandals Bait
                    price: 800
                    quantity: 5
                    size: large
                    color: black
                  totalCartPrice: 2800
                  totalCartQuantity: 8
                  code: '12345678910'
                  paymentMethod: Card
            example:
              auctionName: Tech Festival
              auctionId: 664cc923e5a1e4b89b7ba353
              status: Pending
              baits:
              - baitId: 6650b8973c45cee34da207cf
                baitName: Mzansi Bait
                price: 800
                quantity: 5
                size: large
                color: black
              - baitId: 6650b8663c45cee34da207cd
                baitName: Sandals Bait
                price: 800
                quantity: 5
                size: large
                color: black
              totalCartPrice: 2800
              totalCartQuantity: 8
              code: '12345678910'
              paymentMethod: Card
        required: true
      responses:
        '200':
          description: ''
          headers: {}
      deprecated: false
      servers:
      - url: https://adlinc-api.onrender.com/api/slaschapp
        variables: {}
  /cart/update-cart/{cartId}:
    patch:
      tags:
      - Cart
      summary: Update Order Status
      operationId: UpdateOrderStatus
      parameters:
      - name: cartId
        in: path
        description: ''
        required: true
        style: simple
        schema:
          type: string
      requestBody:
        description: ''
        content:
          application/json:
            schema:
              allOf:
              - $ref: '#/components/schemas/UpdateOrderStatusRequest'
              - example:
                  status: Expired
            example:
              status: Expired
        required: true
      responses:
        '200':
          description: ''
          headers: {}
      deprecated: false
      security:
      - bearer: []
      servers:
      - url: https://adlinc-api.onrender.com/api/slaschapp
        variables: {}
  /cart/orders:
    get:
      tags:
      - Cart
      summary: Get All Orders
      operationId: GetAllOrders
      parameters: []
      responses:
        '200':
          description: ''
          headers: {}
      deprecated: false
      security:
      - bearer: []
      servers:
      - url: https://adlinc-api.onrender.com/api/slaschapp
        variables: {}
  /category/single/{categoryID}:
    get:
      tags:
      - Categories
      summary: Get a single category
      operationId: Getasinglecategory
      parameters:
      - name: categoryID
        in: path
        description: ''
        required: true
        style: simple
        schema:
          type: string
      responses:
        '200':
          description: ''
          headers: {}
      deprecated: false
      servers:
      - url: https://adlinc-api.onrender.com/api/slaschapp
        variables: {}
  /category/all:
    get:
      tags:
      - Categories
      summary: Get All Categories
      operationId: GetAllCategories1
      parameters: []
      responses:
        '200':
          description: ''
          headers: {}
      deprecated: false
      servers:
      - url: https://adlinc-api.onrender.com/api/slaschapp
        variables: {}
  /category/delete/{categoryID}:
    patch:
      tags:
      - Categories
      summary: Delete Category
      operationId: DeleteCategory
      parameters:
      - name: categoryID
        in: path
        description: ''
        required: true
        style: simple
        schema:
          type: string
      responses:
        '200':
          description: ''
          headers: {}
      deprecated: false
      servers:
      - url: https://adlinc-api.onrender.com/api/slaschapp
        variables: {}
  /category/update/{categoryID}:
    patch:
      tags:
      - Categories
      summary: Update A Category
      operationId: UpdateACategory
      parameters:
      - name: categoryID
        in: path
        description: ''
        required: true
        style: simple
        schema:
          type: string
      requestBody:
        description: ''
        content:
          application/json:
            schema:
              allOf:
              - $ref: '#/components/schemas/UpdateACategoryRequest'
              - example:
                  categoryName: Technology
                  categoryImage: Programming Image
            example:
              categoryName: Technology
              categoryImage: Programming Image
        required: true
      responses:
        '200':
          description: ''
          headers: {}
      deprecated: false
      servers:
      - url: https://adlinc-api.onrender.com/api/slaschapp
        variables: {}
  /category:
    post:
      tags:
      - Categories
      summary: Create A Category
      operationId: CreateACategory
      parameters: []
      requestBody:
        description: ''
        content:
          application/json:
            schema:
              allOf:
              - $ref: '#/components/schemas/CreateACategoryRequest'
              - example:
                  categoryName: Technology
                  categoryImage: Tech Image
            example:
              categoryName: Technology
              categoryImage: Tech Image
        required: true
      responses:
        '200':
          description: ''
          headers: {}
      deprecated: false
      servers:
      - url: https://adlinc-api.onrender.com/api/slaschapp
        variables: {}
  /transaction/bait/account:
    post:
      tags:
      - Payments
      summary: Add Bank Card
      operationId: AddBankCard
      parameters: []
      responses:
        '200':
          description: ''
          headers: {}
      deprecated: false
  /transaction/bait/transfer:
    post:
      tags:
      - Payments
      summary: Transfer Funds
      operationId: TransferFunds
      parameters: []
      responses:
        '200':
          description: ''
          headers: {}
      deprecated: false
  /master/search:
    get:
      tags:
      - Search
      summary: Master Search
      operationId: MasterSearch
      parameters:
      - name: query
        in: query
        description: ''
        required: true
        style: form
        explode: true
        schema:
          type: string
      responses:
        '200':
          description: ''
          headers: {}
      deprecated: false
      servers:
      - url: https://adlinc-api.onrender.com/api/slaschapp
        variables: {}
  /feeds/all/users:
    get:
      tags:
      - Feeds
      summary: Users Feed
      operationId: UsersFeed
      parameters: []
      responses:
        '200':
          description: ''
          headers: {}
      deprecated: false
      servers:
      - url: https://adlinc-api.onrender.com/api/slaschapp
        variables: {}
  /feeds/all/owners:
    get:
      tags:
      - Feeds
      summary: Business Owners Feed
      operationId: BusinessOwnersFeed
      parameters: []
      responses:
        '200':
          description: ''
          headers: {}
      deprecated: false
      servers:
      - url: https://adlinc-api.onrender.com/api/slaschapp
        variables: {}
  /feeds/all/auctions:
    get:
      tags:
      - Feeds
      summary: Auctions Feed
      operationId: AuctionsFeed
      parameters: []
      responses:
        '200':
          description: ''
          headers: {}
      deprecated: false
      servers:
      - url: https://adlinc-api.onrender.com/api/slaschapp
        variables: {}
  /feeds/all/baits:
    get:
      tags:
      - Feeds
      summary: Baits Feed
      operationId: BaitsFeed
      parameters: []
      responses:
        '200':
          description: ''
          headers: {}
      deprecated: false
      servers:
      - url: https://adlinc-api.onrender.com/api/slaschapp
        variables: {}
components:
  schemas:
    RegisterUserProfileRequest:
      title: RegisterUserProfileRequest
      required:
      - firstname
      - secondname
      - surname
      - profilePicture
      - phoneNumber
      - email
      - password
      - AcceptTermsAndConditions
      - locationOrAddress
      - birthday
      - educationStatus
      - gender
      - wallet
      - interests
      type: object
      properties:
        firstname:
          type: string
        secondname:
          type: string
        surname:
          type: string
        profilePicture:
          type: string
        phoneNumber:
          type: string
        email:
          type: string
        password:
          type: string
        AcceptTermsAndConditions:
          type: string
        locationOrAddress:
          type: string
        birthday:
          type: string
        educationStatus:
          type: string
        gender:
          type: string
        wallet:
          type: string
        interests:
          type: string
      example:
        firstname: tank
        secondname: michael
        surname: davis
        profilePicture: https://images.pexels.com/photos/5764701/pexels-photo-5764701.png?auto=compress&cs=tinysrgb&w=600
        phoneNumber: '076981284'
        email: tank@gmail.com
        password: davis
        AcceptTermsAndConditions: Yes
        locationOrAddress: Durban,South Africa
        birthday: 1996/07/12
        educationStatus: Tertiary
        gender: male
        wallet: Capitec Wallet
        interests: Food And Drinks
    LoginUserRequest:
      title: LoginUserRequest
      required:
      - email
      - password
      type: object
      properties:
        email:
          type: string
        password:
          type: string
      example:
        email: lizwi@gmail.com
        password: lizwi123
    UserPasswordResetRequest:
      title: UserPasswordResetRequest
      required:
      - newPassword
      - email
      type: object
      properties:
        newPassword:
          type: string
        email:
          type: string
      example:
        newPassword: lizwi
        email: saliba@gmail.com
    UserForgotPasswordRequest:
      title: UserForgotPasswordRequest
      required:
      - email
      type: object
      properties:
        email:
          type: string
      example:
        email: saliba@gmail.com
    CreateBusinessRequest:
      title: CreateBusinessRequest
      required:
      - BusinessName
      - PhoneNumber
      - BusinessEmail
      - AcceptTermsAndConditions
      - BusinessCategory
      - BusinessLocation
      - BusinessHours
      - BusinessLogo
      - verificationDoc
      - status
      - socials
      type: object
      properties:
        BusinessName:
          type: string
        PhoneNumber:
          type: string
        BusinessEmail:
          type: string
        AcceptTermsAndConditions:
          type: string
        BusinessCategory:
          type: string
        BusinessLocation:
          type: string
        BusinessHours:
          type: string
        BusinessLogo:
          type: string
        verificationDoc:
          type: string
        status:
          type: string
        socials:
          type: string
      example:
        BusinessName: Lizwi's Tech Store
        PhoneNumber: '04486899921'
        BusinessEmail: LizwiTech@gmail.com
        AcceptTermsAndConditions: Yes
        BusinessCategory: Tech And Electronics
        BusinessLocation: Durban,KwaZulu-Natal
        BusinessHours: 07:00-16:00,Mon-Fri
        BusinessLogo: https://images.pexels.com/photos/2417848/pexels-photo-2417848.jpeg?auto=compress&cs=tinysrgb&w=600
        verificationDoc: https://media.istockphoto.com/id/1448013633/photo/employment-eligibility-verification-form.jpg?b=1&s=612x612&w=0&k=20&c=wIqK_DjjZcFjSmL4Jf9SZ-FAN0MF32DZEhsxllGk1GY=
        status: Active
        socials: facebook
    UpdateSingleBusinessRequest:
      title: UpdateSingleBusinessRequest
      required:
      - BusinessName
      - PhoneNumber
      - BusinessEmail
      - AcceptTermsAndConditions
      - BusinessCategory
      - BusinessLocation
      - BusinessHours
      - verificationDoc
      - status
      - socials
      type: object
      properties:
        BusinessName:
          type: string
        PhoneNumber:
          type: string
        BusinessEmail:
          type: string
        AcceptTermsAndConditions:
          type: string
        BusinessCategory:
          type: string
        BusinessLocation:
          type: string
        BusinessHours:
          type: string
        verificationDoc:
          type: string
        status:
          type: string
        socials:
          type: string
      example:
        BusinessName: William Beauty
        PhoneNumber: '0718999211'
        BusinessEmail: William@gmail.com
        AcceptTermsAndConditions: Yes
        BusinessCategory: Beauty And Cosmetics
        BusinessLocation: Durban,KwaZulu-Natal
        BusinessHours: 07:00-16:00,Mon-Fri
        verificationDoc: verificationDoc string
        status: pending
        socials: twitter
    CreateAuctionRequest:
      title: CreateAuctionRequest
      required:
      - campaignName
      - campaignDescription
      - campaignBudget
      - campaignDailyBudget
      - campaignStartDate
      - interests
      type: object
      properties:
        campaignName:
          type: string
        campaignDescription:
          type: string
        campaignBudget:
          type: integer
          format: int32
        campaignDailyBudget:
          type: integer
          format: int32
        campaignStartDate:
          type: string
        interests:
          type: string
      example:
        campaignName: Fashion Festival
        campaignDescription: Fashion Festival For The Ages
        campaignBudget: 58000
        campaignDailyBudget: 5000
        campaignStartDate: 22 October 2024
        interests: Technology
    UpdateAuctionRequest:
      title: UpdateAuctionRequest
      required:
      - campaignName
      - campaignDescription
      - campaignBudget
      - campaignDailyBudget
      - campaignStartDate
      - checkInStoreAvailability
      - percentageDiscount
      - interests
      - baitPlant
      type: object
      properties:
        campaignName:
          type: string
        campaignDescription:
          type: string
        campaignBudget:
          type: string
        campaignDailyBudget:
          type: string
        campaignStartDate:
          type: string
        checkInStoreAvailability:
          type: string
        percentageDiscount:
          type: string
        interests:
          type: string
        baitPlant:
          allOf:
          - $ref: '#/components/schemas/BaitPlant'
          - {}
      example:
        campaignName: ''
        campaignDescription: ''
        campaignBudget: ''
        campaignDailyBudget: ''
        campaignStartDate: ''
        checkInStoreAvailability: ''
        percentageDiscount: ''
        interests: ''
        baitPlant:
          name: ''
          baitPlantDescription: ''
          price: ''
          photos: ''
    BaitPlant:
      title: BaitPlant
      required:
      - name
      - baitPlantDescription
      - price
      - photos
      type: object
      properties:
        name:
          type: string
        baitPlantDescription:
          type: string
        price:
          type: string
        photos:
          type: string
      example:
        name: ''
        baitPlantDescription: ''
        price: ''
        photos: ''
    UpdateBusinessOwnerRequest:
      title: UpdateBusinessOwnerRequest
      required:
      - firstname
      - secondname
      - surname
      - profilePicture
      - phoneNumber
      - email
      - password
      - AcceptTermsAndConditions
      - locationOrAddress
      - birthday
      - IdNumber
      - IdDocumentLink
      - gender
      - resetToken
      - resetTokenExpiration
      type: object
      properties:
        firstname:
          type: string
        secondname:
          type: string
        surname:
          type: string
        profilePicture:
          type: string
        phoneNumber:
          type: string
        email:
          type: string
        password:
          type: string
        AcceptTermsAndConditions:
          type: string
        locationOrAddress:
          type: string
        birthday:
          type: string
        IdNumber:
          type: string
        IdDocumentLink:
          type: string
        gender:
          type: string
        resetToken:
          type: string
        resetTokenExpiration:
          type: string
      example:
        firstname: Carlos
        secondname: Alberto
        surname: Riberio
        profilePicture: Lucas's photo string
        phoneNumber: '0812344905'
        email: lucasR@gmail.com
        password: lucas123
        AcceptTermsAndConditions: Yes
        locationOrAddress: Cairo,Egypt
        birthday: 27/09/1975
        IdNumber: '8905285921090'
        IdDocumentLink: document link
        gender: male
        resetToken: generated by forgot password
        resetTokenExpiration: generated by forgot password endpoint
    RegisterBusinessOwnerProfileRequest:
      title: RegisterBusinessOwnerProfileRequest
      required:
      - firstname
      - secondname
      - surname
      - profilePicture
      - phoneNumber
      - email
      - password
      - AcceptTermsAndConditions
      - locationOrAddress
      - birthday
      - IdNumber
      - IdDocumentLink
      - gender
      type: object
      properties:
        firstname:
          type: string
        secondname:
          type: string
        surname:
          type: string
        profilePicture:
          type: string
        phoneNumber:
          type: string
        email:
          type: string
        password:
          type: string
        AcceptTermsAndConditions:
          type: string
        locationOrAddress:
          type: string
        birthday:
          type: string
        IdNumber:
          type: string
        IdDocumentLink:
          type: string
        gender:
          type: string
      example:
        firstname: peter
        secondname: king
        surname: peterson
        profilePicture: https://images.pexels.com/photos/733872/pexels-photo-733872.jpeg?auto=compress&cs=tinysrgb&w=600
        phoneNumber: '34'
        email: peterson@gmail.com
        password: mathews12
        AcceptTermsAndConditions: Yes
        locationOrAddress: Johannesburg,South Africa
        birthday: 27/09/1985
        IdNumber: '8905285921090'
        IdDocumentLink: document link
        gender: male
    LoginBusinessOwnerRequest:
      title: LoginBusinessOwnerRequest
      required:
      - email
      - password
      type: object
      properties:
        email:
          type: string
        password:
          type: string
      example:
        email: lizwi@gmail.com
        password: lizwi123
    BusinessOwnerPasswordResetRequest:
      title: BusinessOwnerPasswordResetRequest
      required:
      - newPassword
      - email
      type: object
      properties:
        newPassword:
          type: string
        email:
          type: string
      example:
        newPassword: lizwi
        email: saliba@gmail.com
    BusinessOwnerForgotPasswordRequest:
      title: BusinessOwnerForgotPasswordRequest
      required:
      - email
      type: object
      properties:
        email:
          type: string
      example:
        email: saliba@gmail.com
    CreateBaitPlantRequest:
      title: CreateBaitPlantRequest
      required:
      - baitPlantName
      - baitPlantDescription
      - checkInStoreAvailability
      - percentageDiscount
      - price
      - color
      - size
      - photos
      type: object
      properties:
        baitPlantName:
          type: string
        baitPlantDescription:
          type: string
        checkInStoreAvailability:
          type: string
        percentageDiscount:
          type: string
        price:
          type: string
        color:
          type: string
        size:
          type: string
        photos:
          type: array
          items:
            type: string
          description: ''
      example:
        baitPlantName: Gaming Bait
        baitPlantDescription: Exclusive Gaming Bait
        checkInStoreAvailability: Yes
        percentageDiscount: 13%
        price: R800
        color: black
        size: large
        photos:
        - https://images.pexels.com/photos/3945688/pexels-photo-3945688.jpeg?auto=compress&cs=tinysrgb&w=600
        - https://images.pexels.com/photos/1082810/pexels-photo-1082810.jpeg?auto=compress&cs=tinysrgb&w=600
        - https://images.pexels.com/photos/3593986/pexels-photo-3593986.jpeg?auto=compress&cs=tinysrgb&w=600
        - https://images.pexels.com/photos/3945659/pexels-photo-3945659.jpeg?auto=compress&cs=tinysrgb&w=600
    UpdateBaitPlantRequest:
      title: UpdateBaitPlantRequest
      required:
      - name
      - baitPlantDescription
      - checkInStoreAvailability
      - percentageDiscount
      - price
      - color
      - size
      - photos
      type: object
      properties:
        name:
          type: string
        baitPlantDescription:
          type: string
        checkInStoreAvailability:
          type: string
        percentageDiscount:
          type: string
        price:
          type: string
        color:
          type: string
        size:
          type: string
        photos:
          type: array
          items:
            type: string
          description: ''
      example:
        name: Data Specialist
        baitPlantDescription: Python,SQL and Analytics
        checkInStoreAvailability: Yes
        percentageDiscount: 44%
        price: R75
        color: Purple
        size: Small
        photos:
        - black image
    AddBaitToCartRequest:
      title: AddBaitToCartRequest
      required:
      - auctionName
      - auctionId
      - status
      - baits
      - totalCartPrice
      - totalCartQuantity
      - code
      - paymentMethod
      type: object
      properties:
        auctionName:
          type: string
        auctionId:
          type: string
        status:
          type: string
        baits:
          type: array
          items:
            $ref: '#/components/schemas/Bait'
          description: ''
        totalCartPrice:
          type: integer
          format: int32
        totalCartQuantity:
          type: integer
          format: int32
        code:
          type: string
        paymentMethod:
          type: string
      example:
        auctionName: Tech Festival
        auctionId: 664cc923e5a1e4b89b7ba353
        status: Pending
        baits:
        - baitId: 6650b8973c45cee34da207cf
          baitName: Mzansi Bait
          price: 800
          quantity: 5
          size: large
          color: black
        - baitId: 6650b8663c45cee34da207cd
          baitName: Sandals Bait
          price: 800
          quantity: 5
          size: large
          color: black
        totalCartPrice: 2800
        totalCartQuantity: 8
        code: '12345678910'
        paymentMethod: Card
    Bait:
      title: Bait
      required:
      - baitId
      - baitName
      - price
      - quantity
      - size
      - color
      type: object
      properties:
        baitId:
          type: string
        baitName:
          type: string
        price:
          type: integer
          format: int32
        quantity:
          type: integer
          format: int32
        size:
          type: string
        color:
          type: string
      example:
        baitId: 6650b8973c45cee34da207cf
        baitName: Mzansi Bait
        price: 800
        quantity: 5
        size: large
        color: black
    UpdateOrderStatusRequest:
      title: UpdateOrderStatusRequest
      required:
      - status
      type: object
      properties:
        status:
          type: string
      example:
        status: Expired
    UpdateACategoryRequest:
      title: UpdateACategoryRequest
      required:
      - categoryName
      - categoryImage
      type: object
      properties:
        categoryName:
          type: string
        categoryImage:
          type: string
      example:
        categoryName: Technology
        categoryImage: Programming Image
    CreateACategoryRequest:
      title: CreateACategoryRequest
      required:
      - categoryName
      - categoryImage
      type: object
      properties:
        categoryName:
          type: string
        categoryImage:
          type: string
      example:
        categoryName: Technology
        categoryImage: Tech Image
  securitySchemes:
    bearer:
      type: http
      scheme: bearer
security: []
tags:
- name: Authentication User
- name: Businesses
- name: Auctions
- name: Business Owner
- name: Authentication Business Owner
- name: Data Collection
- name: Admin
- name: Bait Plants
- name: Profiles
- name: Cart
- name: Categories
- name: Payments
- name: Search
- name: Feeds