openapi: 3.0.0
info:
  title: adlinc-API
  contact: {}
  version: '1.0'
servers:
- url: https://adlinc-api.onrender.com/api/slaschapp
  variables: {}
paths:
  /auth/register:
    post:
      tags:
      - Authentication
      summary: Register  User
      operationId: RegisterUser
      parameters: []
      requestBody:
        description: ''
        content:
          application/json:
            schema:
              allOf:
              - $ref: '#/components/schemas/RegisterUserRequest'
              - example:
                  firstname: Wandile
                  secondname: Bernard
                  surname: Nzama
                  email: nzama@gmail.com
                  password: secret3
                  AcceptTermsAndConditions: Yes
                  locationOrAddress: Kimberley,South Africa
                  birthday: 1996/07/12
                  educationStatus: Tertiary
                  gender: male
                  interests: Fashion And Beauty
            example:
              firstname: Wandile
              secondname: Bernard
              surname: Nzama
              email: nzama@gmail.com
              password: secret3
              AcceptTermsAndConditions: Yes
              locationOrAddress: Kimberley,South Africa
              birthday: 1996/07/12
              educationStatus: Tertiary
              gender: male
              interests: Fashion And Beauty
        required: true
      responses:
        '200':
          description: ''
          headers: {}
      deprecated: false
      security: []
      servers:
      - url: https://adlinc-api.onrender.com/api/slaschapp
        variables: {}
  /auth/login:
    post:
      tags:
      - Authentication
      summary: Login User
      operationId: LoginUser
      parameters: []
      requestBody:
        description: ''
        content:
          application/json:
            schema:
              allOf:
              - $ref: '#/components/schemas/LoginUserRequest'
              - example:
                  email: zond0@gmail.com
                  password: secret1
            example:
              email: zond0@gmail.com
              password: secret1
        required: true
      responses:
        '200':
          description: ''
          headers: {}
      deprecated: false
      security: []
      servers:
      - url: https://adlinc-api.onrender.com/api/slaschapp
        variables: {}
  /business:
    post:
      tags:
      - Business Routes
      summary: Create New Business
      operationId: CreateNewBusiness
      parameters: []
      requestBody:
        description: ''
        content:
          application/json:
            schema:
              allOf:
              - $ref: '#/components/schemas/CreateNewBusinessRequest'
              - example:
                  BusinessName: Zondi Beauty
                  PhoneNumber: '0718999210'
                  BusinessEmail: ZondiBeauty@gmail.com
                  AcceptTermsAndConditions: Yes
                  VerificationCode: '56342'
                  BusinessCategory: Beauty And Cosmetics
                  BusinessLocation: Port Shepstone,KwaZulu-Natal
                  BusinessHours: 07:00-16:00,Mon-Fri
            example:
              BusinessName: Zondi Beauty
              PhoneNumber: '0718999210'
              BusinessEmail: ZondiBeauty@gmail.com
              AcceptTermsAndConditions: Yes
              VerificationCode: '56342'
              BusinessCategory: Beauty And Cosmetics
              BusinessLocation: Port Shepstone,KwaZulu-Natal
              BusinessHours: 07:00-16:00,Mon-Fri
        required: true
      responses:
        '200':
          description: ''
          headers: {}
      deprecated: false
      security:
      - bearer: []
      servers:
      - url: https://adlinc-api.onrender.com/api/slaschapp
        variables: {}
    get:
      tags:
      - Business Routes
      summary: Get All Businesses
      operationId: GetAllBusinesses
      parameters: []
      responses:
        '200':
          description: ''
          headers: {}
      deprecated: false
      security:
      - bearer: []
      servers:
      - url: https://adlinc-api.onrender.com/api/slaschapp
        variables: {}
  /business/65cbbbafe516b5a38fa0cd75:
    get:
      tags:
      - Business Routes
      summary: Get Single Business
      operationId: GetSingleBusiness
      parameters: []
      responses:
        '200':
          description: ''
          headers: {}
      deprecated: false
      security:
      - bearer: []
      servers:
      - url: https://adlinc-api.onrender.com/api/slaschapp
        variables: {}
  /business/{businessId}:
    parameters:
      - in: path
        name: businessId
        schema:
          type: integer
        required: true
        description: The Business ID
    delete:
      tags:
      - Business Routes
      summary: Delete Business
      operationId: DeleteBusiness
      parameters: []
      responses:
        '200':
          description: ''
          headers: {}
      deprecated: false
      security:
      - bearer: []
      servers:
      - url: https://adlinc-api.onrender.com/api/slaschapp
        variables: {}
    patch:
      tags:
      - Business Routes
      summary: Update Single Business
      operationId: UpdateSingleBusiness
      parameters: []
      responses:
        '200':
          description: ''
          headers: {}
      deprecated: false
      servers:
      - url: https://adlinc-api.onrender.com/api/slaschapp
        variables: {}
  /search:
    get:
      tags:
      - Business Routes
      summary: Business Search
      operationId: BusinessSearch
      parameters:
      - name: BusinessCategory
        in: query
        description: ''
        required: true
        style: form
        explode: true
        schema:
          type: string
          example: Beauty
      responses:
        '200':
          description: ''
          headers: {}
      deprecated: false
      security:
      - bearer: []
      servers:
      - url: https://adlinc-api.onrender.com/api/slaschapp
        variables: {}
  /business/65dd60d7ba1079c58bd4917d/auction:
    post:
      tags:
      - Auction Routes
      summary: Create Auction
      operationId: CreateAuction
      parameters: []
      requestBody:
        description: ''
        content:
          application/json:
            schema:
              allOf:
              - $ref: '#/components/schemas/CreateAuctionMaterialRequest'
              - example:
                  campaignName: Fish And Chips
                  campaignDescription: High Quality Fashion
                  campaignBudget: R500
                  campaignDailyBudget: R123
                  campaignStartDate: 12-06-1995
                  checkInStoreAvailability: Yes
                  percentageDiscount: 12%
                  interests: Food And Drinks
                  baitPlant:
                    name: Duck Fish
                    baitPlantDescription: Quality Duck Dish
                    price: R400
                    photos: Duck photos
            example:
              campaignName: Fish And Chips
              campaignDescription: High Quality Fashion
              campaignBudget: R500
              campaignDailyBudget: R123
              campaignStartDate: 12-06-1995
              checkInStoreAvailability: Yes
              percentageDiscount: 12%
              interests: Food And Drinks
              baitPlant:
                name: Duck Fish
                baitPlantDescription: Quality Duck Dish
                price: R400
                photos: Duck photos
        required: true
      responses:
        '200':
          description: ''
          headers: {}
      deprecated: false
      security:
      - bearer: []
      servers:
      - url: https://adlinc-api.onrender.com/api/slaschapp
        variables: {}
  /business/65dd60d7ba1079c58bd4917d/search/auction:
    get:
      tags:
      - Auction Routes
      summary: Auction Search
      operationId: AuctionSearch
      parameters:
      - name: campaignName
        in: query
        description: ''
        required: true
        style: form
        explode: true
        schema:
          type: string
          example: Stake
      - name: campaignBudget
        in: query
        description: ''
        required: true
        style: form
        explode: true
        schema:
          type: string
          example: R500
      responses:
        '200':
          description: ''
          headers: {}
      deprecated: false
      security:
      - bearer: []
      servers:
      - url: https://adlinc-api.onrender.com/api/slaschapp
        variables: {}
  /business/65d20ec7cde3eadfa7175962/auction/567688665654:
    patch:
      tags:
      - Auction Routes
      summary: Update Auction
      operationId: UpdateAuction
      parameters: []
      responses:
        '200':
          description: ''
          headers: {}
      deprecated: false
      security:
      - bearer: []
      servers:
      - url: https://adlinc-api.onrender.com/api/slaschapp
        variables: {}
    get:
      tags:
      - Auction Routes
      summary: Get Single Auction
      operationId: GetSingleAuction
      parameters: []
      responses:
        '200':
          description: ''
          headers: {}
      deprecated: false
      servers:
      - url: https://adlinc-api.onrender.com/api/slaschapp
        variables: {}
    delete:
      tags:
      - Auction Routes
      summary: Delete An Auction
      operationId: DeleteAnAuction
      parameters: []
      responses:
        '200':
          description: ''
          headers: {}
      deprecated: false
      servers:
      - url: https://adlinc-api.onrender.com/api/slaschapp
        variables: {}
  /business/65cbbbafe516b5a38fa0cd75/auction:
    get:
      tags:
      - Auction Routes
      summary: Get All Auctions
      operationId: GetAllAuctions
      parameters: []
      responses:
        '200':
          description: ''
          headers: {}
      deprecated: false
      security:
      - bearer: []
      servers:
      - url: https://adlinc-api.onrender.com/api/slaschapp
        variables: {}
  /business/owner:
    post:
      tags:
      - Business Owner
      summary: Create Business Owner
      operationId: CreateBusinessOwner
      parameters: []
      responses:
        '200':
          description: ''
          headers: {}
      deprecated: false
      servers:
      - url: https://adlinc-api.onrender.com/api/slaschapp
        variables: {}
    get:
      tags:
      - Business Owner
      summary: Get All Business Owners
      operationId: GetAllBusinessOwners
      parameters: []
      responses:
        '200':
          description: ''
          headers: {}
      deprecated: false
      servers:
      - url: https://adlinc-api.onrender.com/api/slaschapp
        variables: {}
  /business/owner/65cbbbafe516b5a38fa0cd75:
    patch:
      tags:
      - Business Owner
      summary: Update Business Owner Details
      operationId: UpdateBusinessOwnerDetails
      parameters: []
      responses:
        '200':
          description: ''
          headers: {}
      deprecated: false
      servers:
      - url: https://adlinc-api.onrender.com/api/slaschapp
        variables: {}
    delete:
      tags:
      - Business Owner
      summary: Delete Business Owner
      operationId: DeleteBusinessOwner
      parameters: []
      responses:
        '200':
          description: ''
          headers: {}
      deprecated: false
      servers:
      - url: https://adlinc-api.onrender.com/api/slaschapp
        variables: {}
    get:
      tags:
      - Business Owner
      summary: Get Single Business Owner
      operationId: GetSingleBusinessOwner
      parameters: []
      responses:
        '200':
          description: ''
          headers: {}
      deprecated: false
      servers:
      - url: https://adlinc-api.onrender.com/api/slaschapp
        variables: {}
  /auth/register/owner:
    post:
      tags:
      - Business Owner
      summary: Register Business Owner
      operationId: RegisterBusinessOwner
      parameters: []
      requestBody:
        description: ''
        content:
          application/json:
            schema:
              allOf:
              - $ref: '#/components/schemas/RegisterBusinessOwnerRequest'
              - example:
                  firstname: Lucas
                  secondname: Riberio
                  surname: Da Silva
                  profilePicture: Lucas's photo
                  businessOwnerLogo: Business Logo Owner
                  phoneNumber: '078234490'
                  email: lucas@gmail.com
                  password: lucas123
                  AcceptTermsAndConditions: Yes
                  locatioOrAddress: Sao Paulo,Brazil
                  birthday: 27/09/1975
                  educationStatus: Tertiary
                  employmentStatus: Employed
                  gender: male
            example:
              firstname: Lucas
              secondname: Riberio
              surname: Da Silva
              profilePicture: Lucas's photo
              businessOwnerLogo: Business Logo Owner
              phoneNumber: '078234490'
              email: lucas@gmail.com
              password: lucas123
              AcceptTermsAndConditions: Yes
              locatioOrAddress: Sao Paulo,Brazil
              birthday: 27/09/1975
              educationStatus: Tertiary
              employmentStatus: Employed
              gender: male
        required: true
      responses:
        '200':
          description: ''
          headers: {}
      deprecated: false
      security: []
      servers:
      - url: https://adlinc-api.onrender.com/api/slaschapp
        variables: {}
  /auth/login/owner:
    post:
      tags:
      - Business Owner
      summary: Login Business Owner
      operationId: LoginBusinessOwner
      parameters: []
      requestBody:
        description: ''
        content:
          application/json:
            schema:
              allOf:
              - $ref: '#/components/schemas/LoginBusinessOwnerRequest'
              - example:
                  email: lucas@gmail.com
                  password: lucas123
            example:
              email: lucas@gmail.com
              password: lucas123
        required: true
      responses:
        '200':
          description: ''
          headers: {}
      deprecated: false
      security: []
      servers:
      - url: https://adlinc-api.onrender.com/api/slaschapp
        variables: {}
components:
  schemas:
    RegisterUserRequest:
      title: RegisterUserRequest
      required:
      - firstname
      - secondname
      - surname
      - email
      - password
      - AcceptTermsAndConditions
      - locationOrAddress
      - birthday
      - educationStatus
      - gender
      - interests
      type: object
      properties:
        firstname:
          type: string
        secondname:
          type: string
        surname:
          type: string
        email:
          type: string
        password:
          type: string
        AcceptTermsAndConditions:
          type: string
        locationOrAddress:
          type: string
        birthday:
          type: string
        educationStatus:
          type: string
        gender:
          type: string
        interests:
          type: string
      example:
        firstname: Wandile
        secondname: Bernard
        surname: Nzama
        email: nzama@gmail.com
        password: secret3
        AcceptTermsAndConditions: Yes
        locationOrAddress: Kimberley,South Africa
        birthday: 1996/07/12
        educationStatus: Tertiary
        gender: male
        interests: Fashion And Beauty
    LoginUserRequest:
      title: LoginUserRequest
      required:
      - email
      - password
      type: object
      properties:
        email:
          type: string
        password:
          type: string
      example:
        email: zond0@gmail.com
        password: secret1
    CreateNewBusinessRequest:
      title: CreateNewBusinessRequest
      required:
      - BusinessName
      - PhoneNumber
      - BusinessEmail
      - AcceptTermsAndConditions
      - VerificationCode
      - BusinessCategory
      - BusinessLocation
      - BusinessHours
      type: object
      properties:
        BusinessName:
          type: string
        PhoneNumber:
          type: string
        BusinessEmail:
          type: string
        AcceptTermsAndConditions:
          type: string
        VerificationCode:
          type: string
        BusinessCategory:
          type: string
        BusinessLocation:
          type: string
        BusinessHours:
          type: string
      example:
        BusinessName: Zondi Beauty
        PhoneNumber: '0718999210'
        BusinessEmail: ZondiBeauty@gmail.com
        AcceptTermsAndConditions: Yes
        VerificationCode: '56342'
        BusinessCategory: Beauty And Cosmetics
        BusinessLocation: Port Shepstone,KwaZulu-Natal
        BusinessHours: 07:00-16:00,Mon-Fri
    CreateAuctionMaterialRequest:
      title: CreateAuctionMaterialRequest
      required:
      - campaignName
      - campaignDescription
      - campaignBudget
      - campaignDailyBudget
      - campaignStartDate
      - checkInStoreAvailability
      - percentageDiscount
      - interests
      - baitPlant
      type: object
      properties:
        campaignName:
          type: string
        campaignDescription:
          type: string
        campaignBudget:
          type: string
        campaignDailyBudget:
          type: string
        campaignStartDate:
          type: string
        checkInStoreAvailability:
          type: string
        percentageDiscount:
          type: string
        interests:
          type: string
        baitPlant:
          allOf:
          - $ref: '#/components/schemas/BaitPlant'
          - {}
      example:
        campaignName: Fish And Chips
        campaignDescription: High Quality Fashion
        campaignBudget: R500
        campaignDailyBudget: R123
        campaignStartDate: 12-06-1995
        checkInStoreAvailability: Yes
        percentageDiscount: 12%
        interests: Food And Drinks
        baitPlant:
          name: Duck Fish
          baitPlantDescription: Quality Duck Dish
          price: R400
          photos: Duck photos
    BaitPlant:
      title: BaitPlant
      required:
      - name
      - baitPlantDescription
      - price
      - photos
      type: object
      properties:
        name:
          type: string
        baitPlantDescription:
          type: string
        price:
          type: string
        photos:
          type: string
      example:
        name: Duck Fish
        baitPlantDescription: Quality Duck Dish
        price: R400
        photos: Duck photos
    RegisterBusinessOwnerRequest:
      title: RegisterBusinessOwnerRequest
      required:
      - firstname
      - secondname
      - surname
      - profilePicture
      - businessOwnerLogo
      - phoneNumber
      - email
      - password
      - AcceptTermsAndConditions
      - locatioOrAddress
      - birthday
      - educationStatus
      - employmentStatus
      - gender
      type: object
      properties:
        firstname:
          type: string
        secondname:
          type: string
        surname:
          type: string
        profilePicture:
          type: string
        businessOwnerLogo:
          type: string
        phoneNumber:
          type: string
        email:
          type: string
        password:
          type: string
        AcceptTermsAndConditions:
          type: string
        locatioOrAddress:
          type: string
        birthday:
          type: string
        educationStatus:
          type: string
        employmentStatus:
          type: string
        gender:
          type: string
      example:
        firstname: Lucas
        secondname: Riberio
        surname: Da Silva
        profilePicture: Lucas's photo
        businessOwnerLogo: Business Logo Owner
        phoneNumber: '078234490'
        email: lucas@gmail.com
        password: lucas123
        AcceptTermsAndConditions: Yes
        locatioOrAddress: Sao Paulo,Brazil
        birthday: 27/09/1975
        educationStatus: Tertiary
        employmentStatus: Employed
        gender: male
    LoginBusinessOwnerRequest:
      title: LoginBusinessOwnerRequest
      required:
      - email
      - password
      type: object
      properties:
        email:
          type: string
        password:
          type: string
      example:
        email: lucas@gmail.com
        password: lucas123
  securitySchemes:
    bearer:
      type: http
      scheme: bearer
security: []
tags:
- name: Authentication
  description: ''
- name: Business Routes
  description: ''
- name: Auction Routes
  description: ''
- name: Business Owner
  description: ''